### ISSUE TITLE
jcenter is deprecated

### ISSUE THREAD

**Issue by daespark** [CirrusMD/CirrusMD-Android-SDK-Example#48]
It is no longer in service as of today. A couple of your dependencies are failing to fetch this makes the projects using your sdk un buildable, please update!

**Comment by daespark** [comment]
Never mind, gradle has partial outage, and jcenter should still allow read indefinitely!

**Comment by DanielGalarza** [comment]
@daespark Yes, this is do to an outage with Gradle. We do plan on removing Jcenter in our SDK very soon, but we're waiting on another dependency to make the update. Since Jcenter is indefinitely read only, our SDK should still work as normal, provided that there aren't any outages like this one 😅 

Gradle Outage: https://status.gradle.com/
